# Generated by Django 3.2.12 on 2025-05-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
